# -*- coding: utf-8 -*-
"""PBL4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSvb-Dk3WEyEUzH0l4HpG6E5B2VRKmfJ
"""

# ==========================================================
# DAIC-WOZ MULTIMODA
# READS FULL DATASET + BATCH TRAINING
# ==========================================================

# ================== MOUNT DRIVE ==================
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# !pip install transformers librosa soundfile -q

import os
import re
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import librosa
import soundfile as sf

from torch.optim import AdamW
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.utils.data import Dataset, DataLoader

from transformers import (
    RobertaTokenizer,
    RobertaModel,
    Wav2Vec2Processor,
    Wav2Vec2Model,
)

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc,
    precision_recall_curve,
    f1_score,
)

# ── Device ─────────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using:", device)

# ================== PATHS ==================
BASE_PATH       = "/content/drive/MyDrive/DAIC WOIZ Dataset"
TRANSCRIPT_PATH = os.path.join(BASE_PATH, "Transcripts")
AUDIO_PATH      = os.path.join(BASE_PATH, "wav")

# ================== LABELS ==================
labels = pd.concat([
    pd.read_csv(os.path.join(BASE_PATH, "train_split_Depression_AVEC2017.csv")),
    pd.read_csv(os.path.join(BASE_PATH, "dev_split_Depression_AVEC2017.csv")),
])[["Participant_ID", "PHQ8_Binary"]].drop_duplicates("Participant_ID")

# ================== TEXT CLEANING ==================
def clean_text(t: str) -> str:
    t = t.lower()
    t = re.sub(r"http\S+", "", t)
    t = re.sub(r"[^a-zA-Z\s]", "", t)
    return t.strip()

# ================== LOAD TRANSCRIPTS ==================
texts, ids = [], []
for f in os.listdir(TRANSCRIPT_PATH):
    if f.endswith("_TRANSCRIPT.csv"):
        pid = int(f.split("_")[0])
        try:
            df = pd.read_csv(os.path.join(TRANSCRIPT_PATH, f), sep="\t")
            df = df[df["speaker"] == "Participant"]
            combined = " ".join(df["value"].astype(str).tolist())
            texts.append(clean_text(combined))
            ids.append(pid)
        except Exception as e:
            print(f"Skipping {f}: {e}")

print(f"Loaded {len(ids)} transcripts")

# ================== TEXT ENCODER (RoBERTa) ==================
tokenizer  = RobertaTokenizer.from_pretrained("roberta-base")
text_model = RobertaModel.from_pretrained("roberta-base")

def encode_texts(text_list):
    all_ids, all_masks = [], []
    for t in text_list:
        enc = tokenizer(
            t,
            max_length=128,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        all_ids.append(enc["input_ids"])
        all_masks.append(enc["attention_mask"])
    return torch.cat(all_ids), torch.cat(all_masks)

input_ids_all, masks_all = encode_texts(texts)

# ================== AUDIO PROCESSOR (Wav2Vec2) ==================
processor   = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
audio_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h")

MAX_AUDIO_LEN = 80_000  # ~5 s at 16 kHz

def load_audio(path: str, augment: bool = False) -> torch.Tensor:
    """Load wav, resample to 16 kHz, sanitise → 1-D tensor."""
    if not os.path.exists(path):
        return torch.zeros(MAX_AUDIO_LEN)
    try:
        y, sr = sf.read(path)
    except Exception:
        return torch.zeros(MAX_AUDIO_LEN)

    y = np.array(y, dtype=np.float32)
    if y.ndim > 1:
        y = y.mean(axis=1)

    y = np.nan_to_num(y, nan=0.0, posinf=0.0, neginf=0.0)

    if sr != 16000:
        y = librosa.resample(y, orig_sr=sr, target_sr=16000)

    # FIX — too short or silent files cause NaN inside Wav2Vec2 CNN layers
    if len(y) < 1600:
        return torch.zeros(MAX_AUDIO_LEN)

    peak = np.abs(y).max()
    if peak > 0:
        y = y / peak

    # Augment only during training
    if augment and np.random.rand() < 0.3:
        y = y + 0.005 * np.random.randn(*y.shape).astype(np.float32)

    y = np.nan_to_num(y, nan=0.0, posinf=1.0, neginf=-1.0)

    inputs = processor(y, sampling_rate=16000, return_tensors="pt", padding=True)
    val = inputs.input_values[0]
    val = torch.nan_to_num(val, nan=0.0, posinf=1.0, neginf=-1.0)
    return val

# ================== MERGE LABELS ==================
label_set = set(labels["Participant_ID"].tolist())

X_ids, X_masks, X_audio, y_all = [], [], [], []

for i, pid in enumerate(ids):
    if pid in label_set:
        X_ids.append(input_ids_all[i])
        X_masks.append(masks_all[i])
        X_audio.append(os.path.join(AUDIO_PATH, f"{pid}_AUDIO.wav"))
        y_all.append(
            int(labels.loc[labels["Participant_ID"] == pid, "PHQ8_Binary"].values[0])
        )

X_ids   = torch.stack(X_ids)
X_masks = torch.stack(X_masks)
y_all   = np.array(y_all, dtype=np.int64)

print("DATA SIZE:", len(y_all))
print("Class distribution (0=non-dep, 1=dep):", np.bincount(y_all))

# ================== DATASET ==================
class DepressionDataset(Dataset):
    def __init__(self, ids, masks, audio_paths, labels, augment=False):
        self.ids         = ids
        self.masks       = masks
        self.audio_paths = audio_paths
        self.labels      = torch.tensor(labels, dtype=torch.float32).unsqueeze(1)
        self.augment     = augment

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, i):
        audio = load_audio(self.audio_paths[i], augment=self.augment)[:MAX_AUDIO_LEN]
        return self.ids[i], self.masks[i], audio, self.labels[i]


def collate_fn(batch):
    ids, masks, audio, labels = zip(*batch)
    audio_padded = torch.nn.utils.rnn.pad_sequence(audio, batch_first=True)
    audio_padded = torch.nan_to_num(audio_padded, nan=0.0)
    return torch.stack(ids), torch.stack(masks), audio_padded, torch.stack(labels)

# ================== MODEL ==================
class DepressionModel(nn.Module):
    def __init__(self, text_encoder, audio_encoder):
        super().__init__()
        self.text_encoder  = text_encoder
        self.audio_encoder = audio_encoder

        self.text_fc  = nn.Linear(768, 256)
        self.audio_fc = nn.Linear(768, 256)

        self.text_norm  = nn.LayerNorm(256)
        self.audio_norm = nn.LayerNorm(256)

        self.classifier = nn.Sequential(
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.4),        # increased from 0.3 → better regularisation
            nn.Linear(128, 1),
        )

    def forward(self, ids, masks, audio):
        t = self.text_encoder(ids, attention_mask=masks).last_hidden_state[:, 0, :]
        t = self.text_norm(torch.relu(self.text_fc(t)))

        a = self.audio_encoder(audio).last_hidden_state
        a = torch.nan_to_num(a, nan=0.0)   # FIX — catch NaN from CNN layers
        a = a.mean(dim=1)
        a = self.audio_norm(torch.relu(self.audio_fc(a)))

        return self.classifier(t + a)

# ================== LOSS ==================
n_neg = int((y_all == 0).sum())
n_pos = int((y_all == 1).sum())
pos_weight = torch.tensor([n_neg / n_pos], dtype=torch.float32).to(device)
loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
print(f"pos_weight = {pos_weight.item():.2f}")

# ================== EARLY STOPPING CLASS ==================
class EarlyStopping:
    """
    Stops training when val loss doesn't improve for `patience` epochs.
    Saves the best model weights automatically.
    """
    def __init__(self, patience=5, min_delta=1e-4):
        self.patience   = patience
        self.min_delta  = min_delta
        self.counter    = 0
        self.best_loss  = np.inf
        self.best_weights = None
        self.stop       = False

    def step(self, val_loss, model):
        if val_loss < self.best_loss - self.min_delta:
            self.best_loss    = val_loss
            self.best_weights = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            self.counter      = 0
        else:
            self.counter += 1
            if self.counter >= self.patience:
                self.stop = True

    def restore(self, model):
        if self.best_weights is not None:
            model.load_state_dict(
                {k: v.to(device) for k, v in self.best_weights.items()}
            )

# ================== HELPER: EVALUATE ONE EPOCH ==================
def evaluate(model, loader):
    """Returns val_loss, probs, gt arrays."""
    model.eval()
    total_loss = 0.0
    all_probs, all_gt = [], []

    with torch.no_grad():
        for ids_b, masks_b, audio_b, yb in loader:
            ids_b   = ids_b.to(device)
            masks_b = masks_b.to(device)
            audio_b = audio_b.to(device)
            yb      = yb.to(device)

            logits = model(ids_b, masks_b, audio_b)
            loss   = loss_fn(logits, yb)
            total_loss += loss.item()

            probs = torch.sigmoid(logits).squeeze().cpu().numpy()
            gt_   = yb.squeeze().cpu().numpy()

            if probs.ndim == 0: probs = probs.reshape(1)
            if gt_.ndim == 0:   gt_   = gt_.reshape(1)

            all_probs.extend(probs.tolist())
            all_gt.extend(gt_.tolist())

    avg_loss = total_loss / max(len(loader), 1)
    all_probs = np.nan_to_num(np.array(all_probs, dtype=np.float32), nan=0.5)
    all_gt    = np.array(all_gt, dtype=np.int32)
    return avg_loss, all_probs, all_gt

# ================== 3-FOLD CROSS VALIDATION ==================
kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

EPOCHS        = 30   # higher ceiling — early stopping will cut it when needed
PATIENCE      = 6    # stop if no improvement for 6 consecutive epochs

fold_results  = []

for fold, (tr_idx, te_idx) in enumerate(kf.split(X_ids, y_all)):

    print(f"\n{'='*55}")
    print(f"  FOLD {fold + 1}")
    print(f"{'='*55}")

    train_ds = DepressionDataset(
        X_ids[tr_idx], X_masks[tr_idx],
        [X_audio[i] for i in tr_idx], y_all[tr_idx],
        augment=True
    )
    val_ds = DepressionDataset(
        X_ids[te_idx], X_masks[te_idx],
        [X_audio[i] for i in te_idx], y_all[te_idx],
        augment=False                   # NO augmentation on val/test
    )

    train_loader = DataLoader(
        train_ds, batch_size=8, shuffle=True,
        num_workers=2, pin_memory=True, collate_fn=collate_fn
    )
    val_loader = DataLoader(
        val_ds, batch_size=8, shuffle=False,
        num_workers=2, pin_memory=True, collate_fn=collate_fn
    )

    # ── Fresh model ────────────────────────────────────────
    model = DepressionModel(text_model, audio_model).to(device)

    for p in model.text_encoder.parameters():  p.requires_grad = False
    for p in model.audio_encoder.parameters(): p.requires_grad = False
    for p in model.text_encoder.encoder.layer[-2:].parameters():   p.requires_grad = True
    for p in model.audio_encoder.encoder.layers[-2:].parameters(): p.requires_grad = True

    opt = AdamW([
        {"params": model.text_fc.parameters(),              "lr": 1e-4},
        {"params": model.audio_fc.parameters(),             "lr": 1e-4},
        {"params": model.text_norm.parameters(),            "lr": 1e-4},
        {"params": model.audio_norm.parameters(),           "lr": 1e-4},
        {"params": model.classifier.parameters(),           "lr": 1e-4},
        {"params": model.text_encoder.encoder.layer[-2:].parameters(),   "lr": 2e-5},
        {"params": model.audio_encoder.encoder.layers[-2:].parameters(), "lr": 2e-5},
    ], weight_decay=0.05)           # increased from 0.01 → stronger regularisation

    # LR scheduler — halve LR if val loss plateaus for 3 epochs
    scheduler = ReduceLROnPlateau(opt, mode="min", factor=0.5, patience=3)

    early_stop = EarlyStopping(patience=PATIENCE)

    # ── Per-epoch tracking ─────────────────────────────────
    train_losses, val_losses  = [], []
    val_accs, val_f1s         = [], []

    # ── Training loop ──────────────────────────────────────
    for ep in range(EPOCHS):
        model.train()
        total_loss = 0.0

        for ids_b, masks_b, audio_b, yb in train_loader:
            ids_b   = ids_b.to(device)
            masks_b = masks_b.to(device)
            audio_b = audio_b.to(device)
            yb      = yb.to(device)

            opt.zero_grad()
            logits = model(ids_b, masks_b, audio_b)

            if torch.isnan(logits).any():
                print(f"  [WARN] NaN logit at epoch {ep+1}, skipping batch")
                continue

            loss = loss_fn(logits, yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            opt.step()
            total_loss += loss.item()

        avg_train_loss = total_loss / max(len(train_loader), 1)

        # ── Validation after every epoch ───────────────────
        val_loss, vprobs, vgt = evaluate(model, val_loader)

        vpred   = (vprobs >= 0.5).astype(int)
        val_acc = (vpred == vgt).mean()
        val_f1  = f1_score(vgt, vpred, zero_division=0)

        train_losses.append(avg_train_loss)
        val_losses.append(val_loss)
        val_accs.append(val_acc)
        val_f1s.append(val_f1)

        print(
            f"  Ep {ep+1:>2}/{EPOCHS} | "
            f"Train Loss: {avg_train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val Acc: {val_acc:.4f} | "
            f"Val F1: {val_f1:.4f}"
        )

        # Scheduler step
        scheduler.step(val_loss)

        # Early stopping step
        early_stop.step(val_loss, model)
        if early_stop.stop:
            print(f"\n  ⏹  Early stopping at epoch {ep+1} "
                  f"(best val loss: {early_stop.best_loss:.4f})")
            break

    # Restore best weights before evaluation
    early_stop.restore(model)
    print(f"  ✅ Restored best weights (val loss: {early_stop.best_loss:.4f})")

    # ── Curve 1: Train vs Val Loss ─────────────────────────
    epochs_ran = len(train_losses)
    ep_range   = range(1, epochs_ran + 1)

    fig, axes = plt.subplots(1, 3, figsize=(16, 4))

    axes[0].plot(ep_range, train_losses, label="Train Loss", linewidth=2)
    axes[0].plot(ep_range, val_losses,   label="Val Loss",   linewidth=2)
    axes[0].set_title(f"Fold {fold+1} — Loss Curves")
    axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss")
    axes[0].legend()

    # ── Curve 2: Val Accuracy per epoch ────────────────────
    axes[1].plot(ep_range, val_accs, color="seagreen", linewidth=2, marker="o", markersize=3)
    axes[1].set_title(f"Fold {fold+1} — Val Accuracy per Epoch")
    axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Accuracy")
    axes[1].set_ylim(0, 1.05)

    # ── Curve 3: Val F1 per epoch ──────────────────────────
    axes[2].plot(ep_range, val_f1s, color="tomato", linewidth=2, marker="o", markersize=3)
    axes[2].set_title(f"Fold {fold+1} — Val F1 (Depressed) per Epoch")
    axes[2].set_xlabel("Epoch"); axes[2].set_ylabel("F1 Score")
    axes[2].set_ylim(0, 1.05)

    plt.tight_layout()
    plt.show()

    # ── Final evaluation with best weights ─────────────────
    _, all_probs, all_gt = evaluate(model, val_loader)

    # Threshold search (maximise depressed-class F1)
    best_t, best_f1 = 0.5, -1.0
    for t in np.arange(0.25, 0.75, 0.05):
        preds_t = (all_probs >= t).astype(int)
        f1 = f1_score(all_gt, preds_t, zero_division=0)
        if f1 > best_f1:
            best_f1, best_t = f1, t

    print(f"\n  Best threshold: {best_t:.2f}  (F1={best_f1:.3f})")
    pred = (all_probs >= best_t).astype(int)
    acc  = (pred == all_gt).mean()
    print(f"  Accuracy: {acc:.4f}")
    print(classification_report(all_gt, pred, zero_division=0,
                                target_names=["Non-Depressed", "Depressed"]))

    # ── Confusion Matrix ───────────────────────────────────
    cm  = confusion_matrix(all_gt, pred)
    fig2, ax = plt.subplots(figsize=(5, 4))
    im = ax.imshow(cm, cmap="Blues")
    ax.set_xticks([0, 1]); ax.set_yticks([0, 1])
    ax.set_xticklabels(["Non-dep", "Dep"])
    ax.set_yticklabels(["Non-dep", "Dep"])
    for r in range(2):
        for c in range(2):
            ax.text(c, r, cm[r, c], ha="center", va="center",
                    color="white" if cm[r, c] > cm.max() / 2 else "black",
                    fontsize=14)
    plt.colorbar(im, ax=ax)
    ax.set_title(f"Confusion Matrix — Fold {fold+1}")
    ax.set_xlabel("Predicted"); ax.set_ylabel("True")
    plt.tight_layout(); plt.show()

    # ── ROC Curve ──────────────────────────────────────────
    fpr, tpr, _ = roc_curve(all_gt, all_probs)
    roc_auc     = auc(fpr, tpr)
    plt.figure(figsize=(5, 4))
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}", linewidth=2)
    plt.plot([0, 1], [0, 1], "k--")
    plt.xlabel("FPR"); plt.ylabel("TPR")
    plt.title(f"ROC Curve — Fold {fold+1}")
    plt.legend(); plt.tight_layout(); plt.show()

    # ── Precision-Recall Curve ─────────────────────────────
    prec, rec, _ = precision_recall_curve(all_gt, all_probs)
    plt.figure(figsize=(5, 4))
    plt.plot(rec, prec, linewidth=2)
    plt.xlabel("Recall"); plt.ylabel("Precision")
    plt.title(f"PR Curve — Fold {fold+1}")
    plt.tight_layout(); plt.show()

    fold_results.append({
        "fold": fold + 1,
        "acc":  acc,
        "auc":  roc_auc,
        "f1":   best_f1,
        "epochs_ran": epochs_ran,
    })

# ================== FINAL SUMMARY ==================
print("\n" + "=" * 55)
print("  CROSS-VALIDATION SUMMARY")
print("=" * 55)
accs = [r["acc"] for r in fold_results]
aucs = [r["auc"] for r in fold_results]
f1s  = [r["f1"]  for r in fold_results]

for r in fold_results:
    print(
        f"  Fold {r['fold']}  "
        f"Acc={r['acc']:.4f}  "
        f"AUC={r['auc']:.4f}  "
        f"F1={r['f1']:.4f}  "
        f"Epochs={r['epochs_ran']}"
    )

print(f"\n  Mean Acc : {np.mean(accs):.4f} ± {np.std(accs):.4f}")
print(f"  Mean AUC : {np.mean(aucs):.4f} ± {np.std(aucs):.4f}")
print(f"  Mean F1  : {np.mean(f1s):.4f}  ± {np.std(f1s):.4f}")

# ── Final summary bar chart ────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(14, 4))
colors = ["steelblue", "seagreen", "tomato"]
fold_labels = [f"Fold {r['fold']}" for r in fold_results]

for ax, metric, vals, title in zip(
    axes,
    ["acc", "auc", "f1"],
    [accs, aucs, f1s],
    ["Accuracy", "AUC", "F1 (Depressed)"]
):
    ax.bar(fold_labels, vals, color=colors)
    ax.axhline(np.mean(vals), color="black", linestyle="--",
               label=f"Mean={np.mean(vals):.3f}")
    ax.set_ylim(0, 1.05)
    ax.set_ylabel(title)
    ax.set_title(f"{title} per Fold")
    ax.legend()

plt.tight_layout()
plt.show()